### Register
POST {{host}}/users
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "user": {
        "email": "{{email}}",
        "password": "{{password}}",
        "username": "{{username}}"
    }
}

### Login /// with token은 Postman 참고
POST {{host}}/users/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "user": {
        "email": "{{email}}",
        "password": "{{password}}"
    }
}

### Current User
GET {{host}}/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{token}}

### Update User
PUT {{host}}/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{token}}

{
    "user": {
        "email": "{{update-email}}",
        "bio": "{{update-bio}}",
        "image": "{{update-image}}"
    }
}