### Profile
GET {{host}}/profiles/{{username}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{token}}

### Follow Profile
POST {{host}}/profiles/{{username}}/follow
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{token}}

### Unfollow Profile
DELETE {{host}}/profiles/{{username}}/follow
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{token}}